// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coklejkbfulvolxurthw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNva2xlamtiZnVsdm9seHVydGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDcxOTcsImV4cCI6MjA3MDQ4MzE5N30.scLRPTmrEAIYmvg6wB2V25l0G0DNguXQ6rHnD5FGKpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});